### ISSUE TITLE
Run attack small tree error

### ISSUE THREAD

**Issue by technickid** [cawka/ndnSIM-ddos-interest-flooding#2]
hi, when i run ./run.py -s attack-small-tree, it's error. 
(my boost version is libboost1.54-dev. I'm using ubuntu 14.04)

Simulating the following scenarios: attack-small-tree
Building graphs for the following scenarios: attack-small-tree
./build/interest-ddos-attack-and-mitigation-scenario --algorithm=fairness --run=1 --topology=small-tree --badCount=1 --goodCount=0 --folder=attackSmallTree --producer=gw --defaultRtt=80ms
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/workerpool-0.9.4-py2.7.egg/workerpool/workers.py", line 36, in run
    job.run()
  File "./run.py", line 58, in run
    subprocess.call (self.cmdline)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by zxr2017** [comment]
Hi，did you solve the problem above？
